### ISSUE TITLE
Events display in gcal

### ISSUE THREAD

**Issue by monochromec** [kewisch/gdata-provider#113]
### Describe the problem and steps to reproduce it:

Open the calendar view in 78.3.2 with a few subscribed gcal calendars. 
The gcal events are only displayed if you click on the visibility icon in the calendar space in the lower left part of the window twice.

### What happened?

gcal are not visible after opening the calendar view.

### What did you expect to happen?

Events would be visible.

### Anything else we should know?

I can only reproduce this on OSX with version 78.3.2. TB versions 78.3.1 and 68.10 on Linux and 78.3.2 on Windows work fine.

**Comment by fthx** [comment]
Confirmed, only since 78.3.2.
Ubuntu 20.04, Thunderbird snap

**Comment by dakirstein** [comment]
Problem as decribed above exists in Windows 10 Ver 2004 Build 19041.546 Thunderibird 78.3.2 
Provider for Google Calendar ver 78.0.1

**Comment by monochromec** [comment]
Forgot to mention this in my initial description: provider version is indeed 78.0.1.

**Comment by chris2553** [comment]
Same thing is happening on Linux. TB version is 78.3.2. Provider version is 78.0.1.

**Comment by kewisch** [comment]
With opening the calendar view, is this reproducible only after a restart, or does it also occur when closing the calendar tab and opening it?

**Comment by monochromec** [comment]
Can be reproduced by simply closing the tab and opening it again (on OSX).

**Comment by chris2553** [comment]
On Linux, I upgraded 78.3.1 to 78.3.2. The first time I started 78.3.2 the calendar was populated with stuff from my
google calendar. After closing TB, on all subsequent starts, the calendar is blank until I hide the google stuff and
then show it again.

**Comment by dakirstein** [comment]
> With opening the calendar view, is this reproducible only after a restart, or does it also occur when closing the calendar tab and opening it?

Regarding Windows installation, each time Thunderbird is started the issue appears. The issue does not reappear until restarting Thunderbird.

**Comment by chris2553** [comment]
Just an update. I've upgraded to TB 78.3.3 and the situation is the same as 78.3.1->78.3.2. One first start, the
calendar is populated with stuff from Google calendar but, on second and subsequent starts, it is blank until hide/show.

**Comment by sanjay** [comment]
I have this issue and sometimes have to hide/show when TB has been running for a while.  I also have a problem where events added to GCal outside of Thunderbird never show up in Thunderbird even though other events nearby (same day or neighboring days) are syncing fine.  Seems related but perhaps not. Linux Mint 20 & TB 78.3.3.

**Comment by dakirstein** [comment]
Running TBird 78.4.0, disabled and then reenabled provider in the add-ons tab. Seems to have solved the problem long term,

**Comment by chris2553** [comment]
Yep, that's fixed it for TB-78.4.0 on Linux, too.

**Comment by monochromec** [comment]
Confirmed fix for OSX as well.

**Comment by PhilAgar** [comment]
I tried this and it didn't fix my calendar, see issue #116

**Comment by fthx** [comment]
Fixed running Ubuntu 20.04 since TB 78.4.0 snap update.

**Comment by philagar16** [comment]
See #119 , I enabled Cookies in the Privacy Settings of TB and it now works

**Comment by fthx** [comment]
No that's another bug. I experienced it too and I enabled cookies too (no third-party cookies necessary) to make it work. But I did not get events displayed until 78.4.0. So cookies are not the key.

**Comment by jkytomak** [comment]
I have cookies enabled and still happens (TB 78.40 on MacOS). I think this is different issue than #119

**Comment by jkytomak** [comment]
Disabling and then reenabling provider in the add-ons tab fixed the problem also for me.

**Comment by ph411** [comment]
It's not a permanent solution. Disabling & re-enabling the addon solves the problem. But the problem resurfaces after a day or two. So, it's just a temporary fix.

**Comment by fthx** [comment]
@ph411 exactly what I experienced and think.

**Comment by kewisch** [comment]
I believe there was a fix in Thunderbird that affects this. Can you try in Thunderbird 91 and re-open if it is still an issue?
