### ISSUE TITLE
Thunderbird no longer processes appointment invitations

### ISSUE THREAD

**Issue by crimle** [kewisch/gdata-provider#191]
### Describe the problem and steps to reproduce it:
- Make sure there is both a Google Mail Account and the corresponding Google Calendar set up in Thunderbird
- Ask anyone to invite you to meeting
- Open the email that has just arrived in your inbox

### What happened?
- There is an error message «No calendar set up with write access for invitations. Please check the calendar properties.» on top of the message 
![Thunderbird Termineinladung](https://user-images.githubusercontent.com/51155809/125184540-eee7d880-e21e-11eb-977c-5f4283794ddf.png)

### What did you expect to happen?
The message should show two buttons in order to accept or decline the invitation

### Anything else we should know?

Thunderbird 78.11.0
Provider for Google Calendar 78.0.1

In a forum I found the solution that has to be applied by the user himself. 
I suggest implementing this solution to the extension:

- close Thunderbird
- open the xpi file using 7-zip
- open the file "background.js" for editing
- search for the line «--original = await messenger.gdata.purgeLegacyPrefs();»
- change to /* await messenger.gdata.purgeLegacyPrefs(); */ or delete it
- save the file and close 7-zip
- click «Yes» in order to apply the changes 
- start Thunderbird and go to Settings > Config
- add the follwing paramateres using «Boolean» and setting any of them to «true»
  calendar.google.enableAttendees
  calendar.google.enableEmailInvitations
  calendar.google.sendEventNotifications
- close and restart Thunderbird

**Comment by mtness** [comment]
"Settings > Config" is found here, btw:
Tools > Options > General [scroll to bottom] > "Config Editor"

**Comment by crimle** [comment]
In fact, **inviting people to a meeting** does not work (in spite of this fix). But after applying this fix I could successfully accept invitations from others. Same for you? 

Unfortunately the developer of this important and useful extension does not seem to be active any more. I opened this issue 17 days ago without any reaction. Or is he/she on holidays? There does not seem to be an alternative so I am considering a donation if there is recognisable progress in maintenance and development of this extension.

**Comment by kewisch** [comment]
Apologies I had not read this earlier. Acknowledging this is an issue, I'm working on a patch.

**Comment by kewisch** [comment]
Fixed in 8a86dd5

**Comment by kewisch** [comment]
Note also I added options UI in abc3a417dcf7b6940f599140523f216eca846af4. This will allow you to change the relevant preferences for attendees and notifications.

**Comment by Steven684** [comment]
Hi, Philipp @kewisch 
Thanks for fixing this!
Any chance you can backport this to 78.0.2?
I'm on TB 78.14.0 and can't seem to upgrade to your 91.0.2...?

**Comment by sbelharbi** [comment]
hi,
i am still having this issue. 
thunderbird: 1:91.9.1+build1-0ubuntu0.22.04.1 (came shipped with ubuntu 22.0)
Provider for Google Calendar: 102.0.0 [installed from thunderbird add-ons manager]
![Screenshot from 2022-06-19 12-47-52](https://user-images.githubusercontent.com/23446793/174491684-366bf6ae-b54a-454c-bcea-2c7d8b722903.png)

i had a local calendar [which allows writing invites in it], and i removed it because it just local. i added a google calendar to sync the calendar leading to this issue.
i've seen this issue reported several times. i am not sure there is a solution today.
if this was fixed, not sure why it is coming back in my setup.

thanks

**Comment by crimle** [comment]
For just a while the extension «Provider for Google Calendar» ist not necessary anymore. Thunderbird supports Google Calendar without any extension. This works fine for me. Also accepting invitations are ok.

**Comment by ps-spark** [comment]
> For just a while the extension «Provider for Google Calendar» ist not necessary anymore. Thunderbird supports Google Calendar without any extension. This works fine for me. Also accepting invitations are ok.

If you need only read access to your Google calendar than it works without any add-on. However, if you need read/write access then you have to install the `Provider for Google Calendar` extension.

https://support.mozilla.org/en-US/kb/using-lightning-google-calendar
