### ISSUE TITLE
Unable to dismiss past repeating events

### ISSUE THREAD

**Issue by ArktinenSieni** [kewisch/gdata-provider#192]
### Describe the problem and steps to reproduce it:

Lightning gives notification of all past repeating events. Attempt to dismiss them does nothing. Closing the notification window only results in Lightning giving the same notifications later.

### What did you expect to happen?

Expected the events to be dismissed, and never see them again.

### Anything else we should know?

Console printed following when I tried to click the "dismiss all" or to dismiss single event.
```
Lightning: [calGoogleCalendar] Modifying item REPEATING_EVENT'S_NAME failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Forbidden"
   }
  ],
  "code": 403,
  "message": "Forbidden"
 }
}
6 gdataCalendar.jsm:567

```

**Comment by vibraniumdev** [comment]
I second that. It's driving me crazy.

**Comment by chartre** [comment]
Same for me. In y case, using a Gmail calendar, so can't assure if the issue is from the notifications or from the read/write to google, which seems also giving me some errors.

**Comment by chartre** [comment]
> Same for me. In y case, using a Gmail calendar, so can't assure if the issue is from the notifications or from the read/write to google, which seems also giving me some errors.

I will update the info of my issue a little, to help with the solving and because is anoying AF and only solution that works for me is to remove the event itself.
- TB 91.0.1
- Calendar is from google but is an account made with my corporate email (I think this shouldn't affect). This calendar It's not publicly shared but added in Lightning by its secret address (in iCal format).
- As a difference from @ArktinenSieni, my logs doesn't show any error, but a `null` and a `skipping item`. Can't tell if these are related or not.

Extracted the log for this issue in the following manner: With the notification already being shown, just cleaned the log window and clicked on dismiss (notification is shown again right after the click). Copied all the entries that appeared in the log, so I assume that the issue may be identified here:

<details>
<summary>Log</summary>

```
Calendar: CalDAV: send: BEGIN:VCALENDAR
[VCALENDAR DATA HERE]
Calendar: CalDAV: send (PUT https://apidata.googleusercontent.com/caldav/v2/ [MY EMAIL ADDRESS] [CALENDAR ADDRESS].ics): BEGIN:VCALENDAR
[VCALENDAR DATA HERE]
Calendar: CalDAV: Item modified successfully on [MY EMAIL ADDRESS]
Calendar: CalDAV: send(https://apidata.googleusercontent.com/caldav/v2/ [MY EMAIL ADDRESS] /events/): <?xml version="1.0" encoding="UTF-8"?>
<C:calendar-multiget xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag/><C:calendar-data/></D:prop><D:href>/caldav/v2/ [MY EMAIL ADDRESS] /events/[CALENDAR ADDRESS].ics</D:href></C:calendar-multiget>
Calendar: CalDAV: send (REPORT https://apidata.googleusercontent.com/caldav/v2/ [MY EMAIL ADDRESS] /events/): <?xml version="1.0" encoding="UTF-8"?>
<C:calendar-multiget xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag/><C:calendar-data/></D:prop><D:href>/caldav/v2/ [MY EMAIL ADDRESS] /events/[CALENDAR ADDRESS].ics</D:href></C:calendar-multiget>
Calendar: CalDAV: recv: null
Calendar: CalDAV: recv: <D:multistatus><D:response><D:href>/caldav/v2/ [MY EMAIL ADDRESS] /events/[CALENDAR ADDRESS].ics</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getetag>"63765081210"</D:getetag>
Calendar: CalDAV: skipping item with unmodified etag : "63765081210"
Calendar: aChangeLogListener=undefined
calendarURI=https://apidata.googleusercontent.com/caldav/v2/ [MY EMAIL ADDRESS] /events/ 
iscached=true
this.mQueuedQueries.length=0
Calendar: [calCachedCalendar] Doing changelog based sync for calendar https://apidata.googleusercontent.com/caldav/v2/ [MY EMAIL ADDRESS] /events/
Calendar: CalDAV: send(https://apidata.googleusercontent.com/caldav/v2/ [MY EMAIL ADDRESS] /events/): <?xml version="1.0" encoding="UTF-8"?>
<sync-collection xmlns="DAV:"><sync-token>/caldav/v2/ [MY EMAIL ADDRESS] /events/sync/ChoIyO/pk7XJ8gIQyO/[TOKEN]==</sync-token><sync-level>1</sync-level><prop><getcontenttype/><getetag/></prop></sync-collection>
Calendar: CalDAV: webdav-sync Token: /caldav/v2/ [MY EMAIL ADDRESS] /events/sync/ChoIyO/pk7XJ8gIQyO/pk7XJ8gIYBSCQw+u6AQ==
Calendar: CalDAV: send (REPORT https://apidata.googleusercontent.com/caldav/v2/ [MY EMAIL ADDRESS] /events/): <?xml version="1.0" encoding="UTF-8"?>
<sync-collection xmlns="DAV:"><sync-token>/caldav/v2/ [MY EMAIL ADDRESS] /events/sync/ChoIyO/pk7XJ8gIQyO/[TOKEN]==</sync-token><sync-level>1</sync-level><prop><getcontenttype/><getetag/></prop></sync-collection>
Calendar: CalDAV: recv:
Calendar: CalDAV: New webdav-sync Token: /caldav/v2/ [MY EMAIL ADDRESS] /events/sync/[TOKEN]==
Calendar: aChangeLogListener=[xpconnect wrapped calIGenericOperationListener]
calendarURI=https://apidata.googleusercontent.com/caldav/v2/ [MY EMAIL ADDRESS] /events/ 
iscached=true
this.mQueuedQueries.length=0
Calendar: [calCachedCalendar] replayChangesOn finished.
Calendar: [calCachedCalendar] sync queue empty.
Calendar: CalDAV: recv: <D:multistatus><D:sync-token>/caldav/v2/ [MY EMAIL ADDRESS] /events/sync/[TOKEN]==</D:sync-token></D:multistatus>
```

</details>

**Comment by applesawse** [comment]
Fun fact: There's actually a setting in there that is something like "don't show alerts for missed events." I checked that box and all the old event alerts went away. It doesn't fix the underlying problem, but it makes it far less annoying.

**Comment by SilverknightFL** [comment]
"Fun fact: There's actually a setting in there..." Where, in there, exactly?

**Comment by SilverknightFL** [comment]
Thank you so much, applesawse!

**Comment by kewisch** [comment]
This should be fixed on the main branch, where I'm no longer sending all properties on a change. This I believe happens when you don't have permission on the main object.

**Comment by chartre** [comment]
Hi @kewisch , thank you for the reply, but I'd appreciate a little more info because, for me, your answer says little on how to solve or address the issue. First of all, what do you mean by "main objet"? The subscribed calendar or the event itself? Second, such permissions are about the subscribed calendar to allow changes from clientes? I can dismiss other events without any problem.
Also the "this should be fixed on the main branch" statement is about an already fixed bug or because this issue should be adressed somewhere else (???).
Thank you for your help.

**Comment by ArktinenSieni** [comment]
> This should be fixed on the main branch, where I'm no longer sending all properties on a change. This I believe happens when you don't have permission on the main object.

If this IS becaous of missing permissions of this "main object", would you @kewisch know where I'd find resources or instructions on how to fix this?

**Comment by vibraniumdev** [comment]
I'm trying to understand what "main object" is as well.

**Comment by kewisch** [comment]
I don't know why I called it main object. I meant you don't own the event, since it is an invitation. The organizer owns it.

I have this fixed for what will be version 91.1.0. I don't have an ETA for it but you can follow #224 dor details

**Comment by alessandromannini** [comment]
> I have this fixed for what will be version 91.1.0. I don't have an ETA for it but you can follow #224 dor details

Hi, 

i use v. 91.3.2but still have this problem. Can you confirm?
Thx

**Comment by rarsa69** [comment]
Hi Philipp,
I am using version 91.5.0 (64-bit)
On debian 11 (bullseye) using the debian repository version of thunderbird.
Thanks for looking into this
