### ISSUE TITLE
No calendars listed, events appear dimmed

### ISSUE THREAD

**Issue by gdsotirov** [kewisch/gdata-provider#33]
In Thunderbird 68.2.2 with Lighting and Provider 68.2.1, I do not see the list of my calendars. Events appear dimmed and when clicked show the information, but it's not possible to save any changes.

P.S. I have general.useragent.compatMode.firefox set to true since the problems from two weeks ago, but Calendar page seems completely dysfunctional again :-(

**Comment by gdsotirov** [comment]
The only thing I hadn't thought of was to clear the cache... and that solved the problem, but only after the first restart. Then it's the same...

**Comment by stm9x9** [comment]
same problem, this was the solution to me: https://github.com/kewisch/gdata-provider/issues/28

**Comment by gdsotirov** [comment]
@stm9x9 As I already wrote in my initial message, I already have general.useragent.compatMode.firefox set to true since two weeks ago, but this only solved the problem with multiple authentications (e.g. like one described in #36). My new problem seems more like #23, because as I workaround I could:
- close Thunderbird;
- clear authentication data;
- start Thunderbird again and authenticate again.

After this everything is fine, but only until the next restart, so it is tedious and irritating. I hope new version is released soon.

**Comment by gdsotirov** [comment]
Same case after just upgrading to Thunderbird 68.3.0...

**Comment by TathKi** [comment]
Hi,
Same issue for me using TB 68.3.1 (32 bits), included lightning 68.3.1.1 and Gdata provider 68.2.1.
The workarround gdsotirov provided and  that is to clear the case works for me.

I have general.useragent.compatMode.firefox set to false.

To avoid having to clear the cache every time, I have added " -purgecaches" to the TB icon command line.

**Comment by gdsotirov** [comment]
> To avoid having to clear the cache every time, I have added " -purgecaches" to the TB icon command line.

An even better workaround @TathKi :-)

**Comment by gdsotirov** [comment]
Any help with this issue? Anybody else having same or similar problem?

I meanwhile made an interesting observation - if I kill the Thunderbird process on the next start the calendars are loaded properly.

**Comment by TathKi** [comment]
Fixed by reinit of the extensions.installedDistroAddon.{e2fda1a4-762b-4020-b5ad-a41df1933103} key as described in https://support.mozilla.org/fr/kb/problemes-mises-jour-agenda-thunderbird#w_lightning-disparaagt-apraes-une-mise-aa-jour-de-thunderbird-versions-stables-et-baeta

**Comment by gdsotirov** [comment]
Thanks for the reference @TathKi - I rehearsed my french with it :-) BTW The english version is at [Calendar updates issues with Thunderbird](https://support.mozilla.org/en-US/kb/calendar-updates-issues-thunderbird#w_lightning-disappears-after-a-thunderbird-update-release-and-beta-versions).

Unfortunately, it did not solve my problem. I tried the procedure on both my office and personal laptops on which I have Thunderbird 68.3.1 with Lightning 68.3.1 and Google Data Provider 68.2.1 for my Google calendars. I had to restart Thunderbird twice, because after step "6. Restart Thunderbird" Lightning is not loaded. It appears dimmed in Extensions with the message "Lightning will be uninstalled after you close this tab."

![lightning_disabled](https://user-images.githubusercontent.com/955033/72138553-b0f1c600-3395-11ea-86e1-5448466b7e38.png)

So I close the tab, restart Thunderbird (again) and my calendars are all fine. However, on the next Thunderbird restart (I do not restart too often, but I still do from time to time) I have the same problem as described in this issue - calendar list it not loaded, events appear dimmed and cannot be edited.

As it appears the problem is actually with Lightning, but I'm still not sure what exactly and how to resolve it completely.

**Comment by rmc-va** [comment]
When I opened Thunderbird today, it and Lightning had updated to 68.4.2 which includes a fix for:

Calendar: Various parts of the calendar UI stopped working when a second Thunderbird window opened

This fix appears to resolve the ghosting of my calendars on Thunderbird. I will add a post here if that changes.

**Comment by TathKi** [comment]
After update to 68.4.2, the calendar disappeared again.
I fixed it again by reinit the "extensions.installedDistroAddon.{e2fda1a4-762b-4020-b5ad-a41df1933103}" key

**Comment by gdsotirov** [comment]
Already upgraded and would check on next Thunderbird restart.

**Comment by rmc-va** [comment]
The problem is gone only for the first TB session after TB and Lightning are updated to 68.4.2.  I have also started a post on the Mozilla TB Forum.  I have gotten lots of suggestions but all of them just make the problem disappear and then pop back up after the session is ended.

Color me extremely frustrated.

**Comment by gdsotirov** [comment]
Yes, I confirm the problem continues to exist after I upgraded and whatever workaround I follow. It's really frustrating. @rmc-va please, share the URL of your post, for reference.

**Comment by rmc-va** [comment]
Sorry - Here's the link to my post on the TB Forum:
https://support.mozilla.org/questions/1278196

**Comment by gdsotirov** [comment]
The workaround for this problem as provided in #47 (and in the referenced Mozilla support request from previous comment) is to choose a different option than "Events in current view". The problem is clearly NOT with gdata-provider, so I'm closing this issue.

Related bugs: [1596919](https://bugzilla.mozilla.org/show_bug.cgi?id=1596919), [1556792](https://bugzilla.mozilla.org/show_bug.cgi?id=1556792)
