### ISSUE TITLE
Some calendar events not displaying in thunderbird

### ISSUE THREAD

**Issue by n00mad** [kewisch/gdata-provider#529]
Just upgraded to tbird 102.4.2 from an earlier version of 102.x.x on macos 11.3.
provider for google is at release 102.0.0.

 Both tbird versions have a problem that some, but not all, calendar entries do not appear especially after February 15, 2023.  They do exist in the google calendar.  New entries that are added display but when the calendar is changed to a different week and then one returns to the week with the newly scheduled entry, it does not display.  But it does appear in the google calendar.

I upgraded from tbird 96.x about a week ago , but I cannot be sure if the  missing calendar entries were displaying in that release before the upgrade to 102.x.x.

**Comment by xjonx1** [comment]
There was an issue with the add-on and is now fixed by the developer. Details here: https://github.com/kewisch/gdata-provider/discussions/519#discussioncomment-4147395

**Comment by n00mad** [comment]
Thanks for the heads up.  My issue (or a variation?) persists. I would restate it as:
With macos, tbird 102.4.2 and Provider for google calendar 120.0.3:
Starting March 1, 2023 onward:
a. nothing displays in the 'day' view   
b. Some, but not all, old calendar events display in the Multiweek and month view.
c. Newly created events do not display in the day, multiweek or monthly view.

Newly created items via the tbird extension 'provider for google 'are populated into the google calendar.

Google calendar displays the expected items, both old and newly created.

Should I create a new issue?

**Comment by markus-hsk** [comment]
I observe a similar problem. Interestingly i can reduce it to this:

**NOT SHOWING**
If i add an event using my Android smartphone (Google calender app V2022.44.0-484930793-release) the event is correctly added to the online calender. Thunderbird though wont show this one.  -> 

If i enter the event online in Google Calender it wont be synced to Thunderbird as well.

**SHOWING**
If i take the way and add the same event in Thunderbird (V102.4.1) / addon (102.0.3) the event will even be synced and also be shown in the Android app.


I can't spot any differences in the shown data on Google Calender. But i assume that there must be some hidden meta data which prevents Thunderbird on showing the event.

This is a serious issue for me. I often add events on the go but at home i rely heavily on thunderbird.

Is there a way to see the logs or something what exactly was received from google? Maybe i can spot the differences there or prepare the filter params to see what might be the reason.

**Comment by hakanyi** [comment]
Latest edit by @markus-hsk seems related to #498

**Comment by kewisch** [comment]
This seems to be a mix of different issues mentioned in this issue now. If unsubscribing and re-subscribing does not fix the issue of events disappearing please file a new issue. I'm going to need a fair bit of debug info, or better yet a reliable way to reproduce. Honestly debugging this kind of issue is super difficult, as it can be sporadic. I also don't have an Android to reproduce this.

I've heard about the issue about events not appearing on Android. Last I heard they are shown on in the browser and Thunderbird, which to me is an issue in the Android app?
