### ISSUE TITLE
No writable calendars are configured for invitations

### ISSUE THREAD

**Issue by timur-tabi** [kewisch/gdata-provider#63]
When I add my Google Calendar using CalDav, everything works.

When I add the same calendar using gdata-provider, I cannot accept invitation sent to me via email, even though the calendar is NOT read-only and I can manually add events.

FYI, I had to use the work-around specified in bug #28 to get gdata-provider to work at all.

I'm using Thunderbird 60.9.0 on Ubuntu 19.04.

**Comment by sheldonmaschmeyer** [comment]
I have the same issue. Looking for a solution.

**Comment by jasonvincik** [comment]
@sheldonmaschmeyer - This has been plaguing me, and your solution totally worked! Thank you!

**Comment by CheariX** [comment]
Unfortunately, `calendar.google.enableEmailInvitations=true` only works, if you have configure a single Google Calendar.
If you have two, only the second Account can be used to accept invitations.

**Comment by unode** [comment]
Also bumped into this and was about to open an issue. Thanks to @sheldonmaschmeyer for the workaround.

Wondering about the default being `false`. Is there a reason for this or alternatively, a reason for it not default to `true`?

**Comment by JanaJarecki** [comment]
I have the same issue as @CheariX, seconding the issue about two calendars.

**Comment by fulcorno** [comment]
> Tools -> Options -> Advanced -> Config Editor
> Set calendar.google.enableEmailInvitations to True

It seems that the enableEmailInvitations property is no longer available in version 78.0.1. Are there any equivalent settings to enable the 'email' property?

**Comment by Pawouek** [comment]
The same as @fulcorno - that mentioned option does not exists. 
Nothing even similar in configuration (_calendar.google*_) :/ 
Anybody have any clue what to do to enable email option?

**Comment by JanaJarecki** [comment]
*bump* is there an update on this?

**Comment by garyhooper** [comment]
Same issue here. Any solution?

**Comment by kienli** [comment]
calendar.google.enableEmailInvitations doesn't exist in TB 78.2.2 either. Do you have any solution?

**Comment by PatrickBauer** [comment]
Same, it looks like thats a new bug, not the same like the one the issue is about. Worked perfectly wie Thunderbird 68. I suggest you subscribe this thread for new information.

**Comment by bkiziuk** [comment]
Same here.
calendar.google.enableEmailInvitations is not available any more after upgrade to TB >=78 and thus it is not possible to accept any invitations.

**Comment by twain28** [comment]
Can confirm this on new TB... (on a Mac TB 78.3.1 64bit)...this is probably because the "calendar" settings syntax has changed in Lightlning...looks like now we now have "calendar.registry.CALENDARREGNUMBER.option" syntax ...so I tried adding a new "_calendar.registry.CALENDARREGNUMBER.enableEmailInvitations_" value, just to test if perchance it would work, but it does not.

**Comment by sgrossberndt** [comment]
I had the same issue and was finally able to solve it! 🥳 
Go to the calendar view, right-click on the calendar, choose "Properties". Here you find an option "Email", which was set to "none" for me. After selecting my Google Email account and saving I am finally able to accept invitations again!

**Comment by seanbright** [comment]
Nothing is going to 'solve' this problem short of a change to the code and a release. The bug is clear:

https://github.com/kewisch/gdata-provider/blob/86bb9ef918535ec0c5a1c425d7fa42f69ea20668/src/legacy/modules/gdataCalendar.jsm#L327-L337

It is referencing a pref that no longer exists.

**Comment by timur-tabi** [comment]
If we already know what the bug is, then why is it taking months to fix it?  Who is responsible for this code?

**Comment by colans** [comment]
@timur-tabi Because folks like yourself are spending time complaining instead of providing pull requests that make it easier for the maintainer to review and merge.  Instead of complaining, why don't you help?

If you're not a developer, you can also offer to pay the maintainer.  That's how free software gets built.  (The software is free, but the labour isn't.)

Comments like yours only serve to spam everyone subscribing to the issue; they don't add any value.

**Comment by seanbright** [comment]
> If you're not a developer, you can also offer to pay the maintainer. That's how free software gets built. (The software is free, but the labour isn't.)

I don't know if there is a policy against linking directly to contribution pages, but you can find the 'Contribute' button on [the project's add-ons page](https://addons.thunderbird.net/en-US/thunderbird/addon/provider-for-google-calendar/).

**Comment by unode** [comment]
> Edit: Oh boy. This works on Thunderbird 78.3.2, with Thunderbird 78.4.0 the "E-Mail" option is gone again. sob

Thunderbird 78.3.3 here and the "E-mail" option is only present for calendars not managed by this plugin.

I think everyone in this thread agrees that a pull request will push things further and lowering the effort bar to the maintainer is the fastest path to a fix.

I just updated to 78.3.3 and started to bump into the most recent issues mentioned here...

**Comment by DominikTrenz** [comment]
There is a workaround until it is fixed: 
Just add the missing config option "calendar.google.enableEmailInvitations".
Go to "about:config" like described above and rightclick -> new -> boolean -> paste "calendar.google.enableEmailInvitations" and select true.
It should work now.

**Comment by gombosg** [comment]
I tried, and the `calendar.google.enableEmailInvitations` config option is magically removed each time I restart TB. But only this - if I create a config with any other name, it is persisted.
Same if I add it to a `user.js` file like
```
user_pref("calendar.google.enableEmailInvitations", true);
user_pref("test.setting", true);
```
If I start TB config editor, the first config item simply won't show up, but the second will. Strange.

**Comment by gombosg** [comment]
It looks like that the [TB 78 compatibility commit](https://github.com/kewisch/gdata-provider/commit/86bb9ef918535ec0c5a1c425d7fa42f69ea20668) did this. Essentially, the bulk of the extension is "legacy" and a wrapper has been created.

For some reason, config keys (prefs) are also considered legacy and are purged in the code:
https://github.com/kewisch/gdata-provider/blob/0d41a4193fc12b6f9a4a6dd09cc7968f27fccd15/src/background.js#L6-L13

But these local storage settings don't seem to show up in the config editor. I'm not even sure if they work any more. Probably it needs some fixing.

**Comment by kewisch** [comment]
The fix here is indeed to change the property value to return the pref from storage.local. That is async, so it looks like we'll need a wrapper that keeps the preference in memory using storage.onChanged. I'd love to fix this immediately, though I'm not doing well on free time currently.

If you want to view storage.local, you can go to add-on debugging and inspect the extension, there is a storage tab which will also contain the extension storage.

**Comment by MatthewVernon** [comment]
Thunderbird 78.4.0 here, and while this provider has worked for me in the past, I now can't find any way to associate an email address with my google calendar (and thus have it usable for accepting invitations). the about:config editor doesn't want to let me create a new property (as suggested by @DominikTrenz above); I'm afraid I don't understand the comment by @kewisch (or at least, not how one might use this to restore the ability to reply to invitations?).

**Comment by gombosg** [comment]
@MatthewVernon tl;dr it's a bug (or missing feature - compatibility with the latest TB extension framework), it needs fixing, and @kewisch will hopefully do that given some free time, unless someone else steps up to fix it. I never touched FF/TB extensions personally so trying to figure everything out on my own would take ages.

**Comment by ALfuhrmann** [comment]
So I ran afoul of this bug, too. I tried using CalDav instead, but could not get it to work consistently.

I unzipped the XPI and looked for the code lines @seanbright mentioned. Changing 

`!Services.prefs.getBoolPref("calendar.google.enableEmailInvitations", false) `
to
`!Services.prefs.getBoolPref("calendar.google.enableEmailInvitations", true) `

there, and at another occurrence seemed like a good idea, so I did it, not knowing what would happen.

Rezpping and installing in Thunderbird 78.4.1 seems to lead to a working calendar with associated mail address:

![image](https://user-images.githubusercontent.com/3731183/98468786-535c1f00-21dc-11eb-9ea0-bfdf20941158.png)

I am going to test it for a few days and then submit a pull request here, if everything works out fine.

You can download the tweaked version [HERE](https://www.dropbox.com/s/65fv2yqzil7oln2/provider_for_google_calendar-78.0.1-tweaked.xpi?dl=0). Please keep in mind that I do not have the slighted idea what I have been doing and cannot take any responsibilities. If you install this and all your mail gets eaten or posted publicly, I will not be held accountable.

(You can open the above file with any ZIP utility and compare it to the original, if you are paranoid. The online changes should be the two lines in gdataCalendar.jsm)

**Comment by gombosg** [comment]
@ALfuhrmann and do accepting/rejecting invitations work properly after this tweak? For me, the menu item shows up as above but I'm still unable to accept invitations.

**Comment by ALfuhrmann** [comment]
@gombosg: yes, it works for me. When I get an invitation mail and hit "accept", it gets added to my first google calendar.
I am not sure if you can do this with more than one Google calendar, but for me this is enough.

**Comment by twain28** [comment]
@ALfuhrmann : first of all, many thanks for your contribution.
I have tested your mod today, and it works somewhat, but not completely, I fear...as far as I understand this, there's probably still something amiss, since I am not able to invite anyone to my events (attendees are not saved, so I guess they are not invited at all)...this is probably related to the fact that I am using not one, not two, but three gcals...and I guess things go rather badly, when the extension has to deal with multiple accounts.
I guess I'll have to wait a little more...thumbs up for the effort, though. We'll get there, eventually...

**Comment by mrkeycode** [comment]
It's so frustrating. Pls fix #Thunderbird @Firefox !!!

**Comment by Rolf185** [comment]
Seems that kewisch is still short on time. So, I've created an interim solution: 
[provider_for_google_calendar_lagacy-78.0.1-tb.zip](https://github.com/kewisch/gdata-provider/files/5611931/provider_for_google_calendar_lagacy-78.0.1-tb.zip)
It's signed with a different id to allow a permanent installation.
The default for enableEmailInvitations and sendEventNotifications is set to true and the purge of the calendar.google branch in legacey options is disabled. Therfore it's also possible to disable both options via the Thunderbird expert options dialog.

@kewisch: What do you plan for the future? Migrate all Services.prefs options to local storage? May be I can contribute some more.

Rolf

**Comment by unode** [comment]
Dear @Rolf185 thanks a lot for the effort but your version still doesn't work for me.
I can see invitations, but adding participants has no effect. No emails are sent and attendees are not saved correctly.

**Comment by Rolf185** [comment]
@unode: Please be sure that you don't set calendar.google.enableEmailInvitations and calendar.google.sendEventNotifications to false in options. If not, can you check if it works with a calendar which is natively supported by lightning? By the way, I didn't change any logic.
Rolf

**Comment by gombosg** [comment]
I also tried forcing the configs but experience the same problem. Looks like some logic change is needed, as well.

**Comment by Coach78** [comment]
I am having the same problem. A fix would be great!

**Comment by seanbright** [comment]
The "me too" comments (along with this comment referencing them) are not helpful. Everyone who uses this extension is affected.

**Comment by noftalette** [comment]
Hi

> 
> 
> @unode: Please be sure that you don't set calendar.google.enableEmailInvitations and calendar.google.sendEventNotifications to false in options. If not, can you check if it works with a calendar which is natively supported by lightning? By the way, I didn't change any logic.
> Rolf

Hi Rolf,
Like unode I can have access to the e-mail field in the calendar property which enables me to link this calendar with an e-mail address. However when I create an event, add an participant and send the invitation, no e-mail is sent, and the participant disappear in the list of participants of the event.
I don't catch your answer ; where do I find  calendar.google.enableEmailInvitations and calendar.google.sendEventNotifications ? In the about:config there are no such options begining with calendar.google...

**Comment by zhamm** [comment]
> 
> 
> Seems that kewisch is still short on time. So, I've created an interim solution:
> [provider_for_google_calendar_lagacy-78.0.1-tb.zip](https://github.com/kewisch/gdata-provider/files/5611931/provider_for_google_calendar_lagacy-78.0.1-tb.zip)
> It's signed with a different id to allow a permanent installation.
> The default for enableEmailInvitations and sendEventNotifications is set to true and the purge of the calendar.google branch in legacey options is disabled. Therfore it's also possible to disable both options via the Thunderbird expert options dialog.
> 
> @kewisch: What do you plan for the future? Migrate all Services.prefs options to local storage? May be I can contribute some more.
> 
> Rolf

Your fix didn't work for me either.  I'm using three different calendars, so that may be the issue.  Thank you for the effort however!

**Comment by GCAPITAINE303** [comment]
Hello
Has anyone found a solution for network invitations and not local? thank you

**Comment by noftalette** [comment]
Let me share you my bypass solution : https://forums.mozfr.org/viewtopic.php?f=4&t=145318&p=911105#p911105

**Comment by Etzix** [comment]
> 
> 
> @unode: Please be sure that you don't set calendar.google.enableEmailInvitations and calendar.google.sendEventNotifications to false in options. If not, can you check if it works with a calendar which is natively supported by lightning? By the way, I didn't change any logic.
> Rolf

This solution works great for me, my onlt issue was the purging of the options and this fixes that. Thank you!

**Comment by unode** [comment]
I had no options in the config editor but the reason @Rolf185 changes weren't working for me was #138.
After working around that one things seem to be back to normal (still testing).

Manually adding/creating the following through the config editor solved it for me:
```
calendar.google.enableAttendees;true
calendar.google.enableEmailInvitations;true
calendar.google.sendEventNotifications;true
```

**Comment by Dyvels** [comment]
adding this three doesn´t change anything for me, the issue with "no writeable calendar" stays :/

**Comment by rolbr** [comment]
Hey @unode
what did you do to 'work around that one' ?

> After working around that one, things seem to be back to normal (still testing).
> ```
> calendar.google.enableAttendees;true
> calendar.google.enableEmailInvitations;true
> calendar.google.sendEventNotifications;true
> ```

Every time I restart Thunderbird, those three keys are removed from config. And without restarting Thunderbird, those keys seem to have no effect. I tried switching between mail accounts, opening/closing folders, triggering mail download/sync manually, refreshing calendars. No dice.

### "SOLUTION" : use CalDAV

1. In [Google Calendar web interface](https://calendar.google.com/calendar/) click the three dots to the right of your calendar
2. select `Settings and Sharing`
3. scroll down to `Calendar Integration` and make note of the calendar's ID
4. In Thunderbird / Lightning add new calendar
5. select `Format: CalDAV`
    - username: your email
    - url/address: `https://apidata.googleusercontent.com/caldav/v2/CALENDAR-ID/events`
    - replace **CALENDAR-ID** with the calendar ID you've noted in step 3
6. click `Next`, adjust settings to your liking, and confirm
7. a popup should appear asking you to log in to your Google account and grant Thunderbird/Lightning access to your calendar
8. a confirmation should appear that the calendar was added successfully 🥳

**Comment by Dyvels** [comment]
Jesus! @rolbr thank you so much, finally a solution after month!

**Comment by colans** [comment]
CalDAV was always the other option for sure, but it wasn't clear to me what the differences are.  According to [Calendar:Using Lightning with Google Calendars](https://wiki.mozilla.org/Calendar:Using_Lightning_with_Google_Calendars):

> The Provider [...] is more reliable w.r.t Alarms and some people say its also faster when refreshing.

...but that wiki page hasn't been updated in 6 years.  More up-to-date information seems to be in [this project's FAQ](https://github.com/kewisch/gdata-provider/wiki/FAQ#why-should-i-use-the-provider-and-not-access-via-caldav):

#### Why should I use the Provider, and not access via CalDAV?

> The Provider predates Google Calendar's CalDAV support and was initially recommended because it was more stable. However, CalDAV support has improved with time and now offers a pretty complete Google Calendar experience. For some people, the Provider for Google Calendar works better than CalDAV. The Provider for Google Calendar also allows access to Google's task lists and there are some extra features in the Provider not available via CalDAV, for example setting EMAIL reminders. It is also easier to set up, a graphical calendar picker is available.

**Comment by rolbr** [comment]
Hey @colans thanks for the background info. I must admit I haven't researched this any further. Top priority was being able to accept Email Invitations. Setting up CalDAV sure is a hassle, having to go through the above steps for each single calendar, 5 in my case, but being able to one-click accept invitations was worth it 😉

**Comment by unode** [comment]
>  what did you do to 'work around that one' ?

Was referring to #138 and including `calendar.google.enableEmailInvitations;true` solved it for me.
I still don't see the calendar drop down but invitations are being picked up.

I just tried the CalDAV suggestion and it seems to work well, with the exception that I can't dismiss some reminders on events I was invited to (but that might be unrelated).

**Comment by colans** [comment]
> I just tried the CalDAV suggestion and it seems to work well, with the exception that I can't dismiss some reminders on events I was invited to (but that might be unrelated).

That's a known issue.  The workaround IIRC is to enable the "Don't show reminders for past events" (or similar, can't remember the exact label).

**Comment by dmarteau** [comment]
@rolbr 

Got the exact the same problem: these keys are dismissed when thunderbird is restarted - Note that this behavior is very specifice to these keys.

**Comment by unode** [comment]
@rolbr and @dmarteau the problem is https://github.com/kewisch/gdata-provider/blob/0d41a4193fc12b6f9a4a6dd09cc7968f27fccd15/src/api/gdata.js#L98 called from https://github.com/kewisch/gdata-provider/blob/0d41a4193fc12b6f9a4a6dd09cc7968f27fccd15/src/background.js#L11 

If you use @Rolf185 version above, this code is commented out so you won't have that problem.

**Comment by yongkhun** [comment]
> 
> 
> I had no options in the config editor but the reason @Rolf185 changes weren't working for me was #138.
> After working around that one, things seem to be back to normal (still testing).
> 
> Manually adding/creating the following through the config editor solved it for me:
> 
> ```
> calendar.google.enableAttendees;true
> calendar.google.enableEmailInvitations;true
> calendar.google.sendEventNotifications;true
> ```

After manually adding the 3 configs above, in order to avoid them being removed when restarting Thunderbird, I found the following works for me:

- Goto your thunderbird local profile folder ..\thunderbirdProfile.default\extensions\
- Find the right xpi file of your installed Provider for Google Calendar extension, which might be any of the {xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}.xpi . If you are not sure which one, just open them one by one using 7-zip and check in the file "manifest.json"
- Open the xpi file with 7-zip (make sure Thunderbird is not running while the xpi file is being opened)
- Edit the file "background.js" and comment out the line:
`/* await messenger.gdata.purgeLegacyPrefs(); */`
- Save and exit 7-zip, and "yes" when prompted whether to update to the archive.

Hope this helps.

**Comment by rascasoft** [comment]
> > I had no options in the config editor, but the reason @Rolf185 changes weren't working for me was #138.
> > After working around that one, things seem to be back to normal (still testing).
> > Manually adding/creating the following through the config editor solved it for me:
> > ```
> > calendar.google.enableAttendees;true
> > calendar.google.enableEmailInvitations;true
> > calendar.google.sendEventNotifications;true
> > ```
> 
> After manually adding the 3 configs above, in order to avoid them being removed when restarting Thunderbird, I found the following works for me:
> 
>     * Goto your thunderbird local profile folder ..\thunderbirdProfile.default\extensions\
> 
>     * Find the right xpi file of your installed Provider for Google Calendar extension, which might be any of the {xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}.xpi . If you are not sure which one, just open them one by one using 7-zip and check in the file "manifest.json"
> 
>     * Open the xpi file with 7-zip (make sure Thunderbird is not running while the xpi file is being opened)
> 
>     * Edit the file "background.js" and comment out the line:
>       `/* await messenger.gdata.purgeLegacyPrefs(); */`
> 
>     * Save and exit 7-zip, and "yes" when prompted whether to update to the archive.
> 
> 
> Hope this helps.

Many thanks @yongkhun , this workaround works as expected. It would be beneficial to create a pull request to get this included in the official release, but we need first to understand what that purge action was meant to. Maybe @kewisch can share some light on this.

**Comment by IanBlakeley** [comment]
Done everything suggested above by @rascasoft , checked the changes to  claendar extension are still there but sadly the changes to the config file are still removed on a restart.

**Comment by adefaria** [comment]
> Hello
> Has anyone found a solution for network invitations and not local? thank you

Not a solution but a work-around. While you can't add people to your event through TB you can make the event then go to calendar.google.com and you can add people to the event there.

**Comment by felix-seifert** [comment]
I applied the settings suggested by @unode and @yongkhun. I added the three suggested config values and edited the relevant `.xpi` file. When I restart TB, the config values are still set. However, the behaviour of calendar invitations is still the same: "No writable calendars are configured for invitations."

**Comment by Crandel** [comment]
>Any ideas what else I could try?

Just set email in calendar properties

**Comment by Daveve200** [comment]
I'm relatively new to using Thunderbird and I simply can't believe it, that such a simple action as accepting a calendar invitation via email would steal over 1.5h of my life. And worse: **no solution yet.** There are lots of outdated posts that talk about TB add-ons that don's even exist anymore, it's surprising that those are still so prominent. - Oh well, **I subscribed to the channel**. Hope a practical solution comes up soon but the longer these things take, the more cumbersome the use of TB and the more likely that people will resort to large-tech solutions with questionable privacy agreements. (different subject, not to be elaborated on in this thread)

**Comment by Rolf185** [comment]
Hi,

although I've done some changes to the gdata-provider plugin I'm not 
using this plugin anymore.

I've defined my Google calendar via caldav:

https://apidata.googleusercontent.com/caldav/v2/<account>@<gmail.com>/events

For me it's working.

Rolf

Am 04.07.2021 um 13:17 schrieb Daveve200:

**Comment by colans** [comment]
To make it more formal, any reason to not deprecate this plugin in favour of the CalDAV approach?

**Comment by Crandel** [comment]
@colans CalDav API is blocked for security issues in my work, so I have no other choices. And editing addon as archive works fine for me. But would be better to create a PR and return this options again

**Comment by colans** [comment]
Issue created at #190.  Please help move that along with PRs, etc.  Thanks!

**Comment by rstuart** [comment]
> To make it more formal, any reason to not deprecate this plugin in favour of the CalDAV approach?

As a number of [people here](https://github.com/kewisch/gdata-provider/issues/63#issuecomment-759584618) and [elsewhere](https://github.com/jobisoft/DAV-4-TbSync/issues/188#issuecomment-725854288) have said, CalDAV has an issue: it doesn't dismiss events properly.  Every time I use it I get lots of reminders about missed events.  I gather people "solve" that but turning notifications for missed events off, but that's not acceptable to everyone.

In the mean time, after [manual editing of the config](https://github.com/kewisch/gdata-provider/issues/63#issuecomment-757062879) Rolf185's [version of this plugin](https://github.com/kewisch/gdata-provider/issues/63#issuecomment-735366481) works perfectly.

That aside, what does depreciating it achieve?  Unless a maintainer steps up it will die regardless of what you do, and if a maintainer does step up it will continue to live regardless of what you do.

**Comment by colans** [comment]
@rstuart You're mostly right, but if folks see the issue it may save them some trouble.  Your comment about turning off missed events would be helpful over there; please add it.

**Comment by ahukkanen** [comment]
> That aside, what does depreciating it achieve? Unless a maintainer steps up it will die regardless of what you do, and if a maintainer does step up it will continue to live regardless of what you do.

Deprecating would at least make it clearer that this add-on is no longer maintained and therefore should not be used.

The most confusing part to me at least is that the official documentation recommends using this add-on with Google calendar:
https://support.mozilla.org/en-US/kb/using-lightning-google-calendar

If that documentation was updated with the CalDAV method, I think it would save a ton of hours in people's productivity not trying to figure out how to fix the issue manually in the add-on but rather relying on the CalDAV method.

> As a number of [people here](https://github.com/kewisch/gdata-provider/issues/63#issuecomment-759584618) and [elsewhere](https://github.com/jobisoft/DAV-4-TbSync/issues/188#issuecomment-725854288) have said, CalDAV has an issue: it doesn't dismiss events properly.

To me this is a smaller issue than forking the add-on, manually editing configuration file and trying out different versions of the extension. Even after all that, I never got calendar invitation reply emails to be sent with the gdata-provider add-on (I just replied directly from GMail).

When switching to the CalDAV method, I sure bumped into the events dismiss issue but for me it was only 3 events where I could not dismiss the old reminders. It was a breeze to go edit those 3 events and remove their notifications manually compared to what needed to be done with gdata-provider.

**Comment by Crandel** [comment]
>I think it would save a ton of hours in people's productivity not trying to figure out how to fix the issue manually in the add-on but rather relying on the CalDAV method.

@ahukkanen As I said in my comment I don't have CalDav API at all and cannot rely on it. @yongkhun method works like a charm and I have no problem with calendar events at all. Please don't touch it if you don't use it

**Comment by ahukkanen** [comment]
@Crandel At least as an official method documented in the official documentation, it should be deprecated because it doesn't work without modifications to the add-on. And if the maintenance is dropped, sooner or later it will be a security issue if people keep relying on 3rd party modifications of the original add-on.

As far as I understood from the discussion, the CalDAV method is the only method right now that works out-of-the-box without modifying any add-on by hand or without modifying any configuration files by hand. I understand that it does not necessarily work for all, but if that is the only option right, I think it should be the preferred one.

**Comment by ahukkanen** [comment]
It actually seems that there was already a pending revision from Mozilla Support forum user [Matt](https://support.mozilla.org/en-US/user/MattAuSupport) regarding the Google Calendar integration documentation.

I added a note there that this add-on does not work perfectly for Thunderbird v78.11.0 or newer with a link to this issue. Here's the latest revision (at this moment):
https://support.mozilla.org/en-US/kb/using-lightning-google-calendar/revision/225291

**Comment by mthskarin** [comment]
This issue has sadly has on and off, stolen many productive hours of my time over the years. I find it strange that it it so hard to get a cloud based calender to work with Thunderbird. (kind of a "must have" for a digital worker). 

I highly appriciate every effort from all developers that makes Thunderbird and its ecosystem work. It is truly amazing to have an open source option outside Exchange and Tech giants. 

That said, I do I second that the Google Calendar plugin should be depricated until this issue is solved, for the sake of saving valuable productive hours of people's time.

The CalDev workaround worked for me  (big thanks to @rolbr for sharing it).

**Comment by kewisch** [comment]
I've identified the cause for this, please expect it to work again in Provider 91.0.2

**Comment by Gwalior-84** [comment]
> 
> 
> I've identified the cause for this, please expect it to work again in Provider 91.0.2

Thanks @kewisch   Is Provider 91.0.2 available?  The latest version available in github is [91.0.0](https://github.com/kewisch/gdata-provider/releases/tag/v91.0.0) and on the Thunderbird Add-ons page is [91.0.1](https://addons.thunderbird.net/en-US/thunderbird/addon/provider-for-google-calendar/versions/?page=1#version-91.0.1).  (How does the Thunderbird Add-ons page get a more recent version that github?)

**Comment by mauromol** [comment]
Any chance to get this fix to a version compatible with Thunderbird 78.x?
No 91 version available yet on Ubuntu 20.04...

**Comment by IanBlakeley** [comment]
> Any chance to get this fix to a version compatible with Thunderbird 78.x? No 91 version available yet on Ubuntu 20.04...

I had this issue as a Mint user. in the end jumped off the lagging version in the repositories and I now use the direct update path from Mozilla

**Comment by MartinX3** [comment]
> Any chance to get this fix to a version compatible with Thunderbird 78.x? No 91 version available yet on Ubuntu 20.04...

I switched from mint to arch linux because of the ubuntu lts update policy.
(I created issue tickets about backporting all the time before, because otherwise they ignored new versions)

**Comment by Crandel** [comment]
Just use AppImage on Ubuntu/Mint. I also use it, works fine

**Comment by MartinX3** [comment]
> Just use Thunderbird 91.3 via AppImage on Ubuntu/Mint. I also use it works fine

Sadly solutions like AppImage, Snap, Flatpak, etc are all having the (dis)advantage to included all needed software libraries.
So if a library needs a minor update from x.y.1 to x.y.2 because of a security bug, you won't get the update via your regular system updates. Instead you need to wait until a new Image for the software got created.

**Comment by Crandel** [comment]
When just use [Ubuntu Mozilla Security ppa](https://ubuntuupdates.org/ppa/ubuntu_mozilla_security?dist=focal) it has the latest version

**Comment by mauromol** [comment]
I think we're going off topic here. The problem is not that all the world must want to get the latest version of Thunderbird at all costs (I don't feel it is necessary for me to upgrade to Thunderbird 91 right now from a feature point of view), but rather that there still are fully supported Thunderbird installation scenarios where this severe bug of gdata-provider currently stands.

So, question is again: is there any hope to get a backport to support Thunderbird 78 or not?

Of course, the maintainer may just respond "no, it's not planned" and I would respect it. After that, it will be my choice to perform all the necessary actions required to update Thunderbird with any of the multiple options there are, or prefer to just wait for Ubuntu to upgrade their official package, if I can live with this problem meanwhile. It's just a matter of personal priorities.

**Comment by Crandel** [comment]
In 91 version there are no needs for this addon anymore, it will automatically pick up your calendar during setup with full synchronization

**Comment by MatthewVernon** [comment]
FWIW, with Thunderbird 78 (and presumably later), I found [these instructions](https://emperor.dreamwidth.org/747469.html) on adding CalDAV support sufficient to get calendar support working without this plugin; mentioning it here in case that's useful...

**Comment by Ryushin** [comment]
> > Just use Thunderbird 91.3 via AppImage on Ubuntu/Mint. I also use it works fine
> 
> Sadly solutions like AppImage, Snap, Flatpak, etc are all having the (dis)advantage to included all needed software libraries. So if a library needs a minor update from x.y.1 to x.y.2 because of a security bug, you won't get the update via your regular system updates. Instead you need to wait until a new Image for the software got created.

I just download the Thunderbird tar ball, put it in /opt, change the ownership to myself and it auto updates like normal.

Though I allowed Thunderbird to update to the latest version and the readability of the fonts being used was terrible, so I downgraded until I have time to get that sorted.

**Comment by MartinX3** [comment]
> > > Just use Thunderbird 91.3 via AppImage on Ubuntu/Mint. I also use it works fine
> > 
> > 
> > Sadly solutions like AppImage, Snap, Flatpak, etc are all having the (dis)advantage to included all needed software libraries. So if a library needs a minor update from x.y.1 to x.y.2 because of a security bug, you won't get the update via your regular system updates. Instead you need to wait until a new Image for the software got created.
> 
> I just download the Thunderbird tar ball, put it in /opt, change the ownership to myself and it auto updates like normal.
> 
> Though I allowed Thunderbird to update to the latest version and the readability of the fonts being used was terrible, so I downgraded until I have time to get that sorted.

That's a bad practice.
`/opt` needs to be owned by `root:root` and software only updated by the administrator (by using sudo).
And never execute a software with `sudo` just to workaround filesystem permissions.

**Comment by Ryushin** [comment]
> > > > Just use Thunderbird 91.3 via AppImage on Ubuntu/Mint. I also use it works fine
> > > 
> > > 
> > > Sadly solutions like AppImage, Snap, Flatpak, etc are all having the (dis)advantage to included all needed software libraries. So if a library needs a minor update from x.y.1 to x.y.2 because of a security bug, you won't get the update via your regular system updates. Instead you need to wait until a new Image for the software got created.
> > 
> > 
> > I just download the Thunderbird tar ball, put it in /opt, change the ownership to myself and it auto updates like normal.
> > Though I allowed Thunderbird to update to the latest version and the readability of the fonts being used was terrible, so I downgraded until I have time to get that sorted.
> 
> That's a bad practice. `/opt` needs to be owned by `root:root` and software only updated by the administrator (by using sudo). And never execute a software with `sudo` just to workaround filesystem permissions.

/opt is owned by root, /opt/thunderbird is owned by me.

**Comment by MartinX3** [comment]
> > > > > Just use Thunderbird 91.3 via AppImage on Ubuntu/Mint. I also use it works fine
> > > > 
> > > > 
> > > > Sadly solutions like AppImage, Snap, Flatpak, etc are all having the (dis)advantage to included all needed software libraries. So if a library needs a minor update from x.y.1 to x.y.2 because of a security bug, you won't get the update via your regular system updates. Instead you need to wait until a new Image for the software got created.
> > > 
> > > 
> > > I just download the Thunderbird tar ball, put it in /opt, change the ownership to myself and it auto updates like normal.
> > > Though I allowed Thunderbird to update to the latest version and the readability of the fonts being used was terrible, so I downgraded until I have time to get that sorted.
> > 
> > That's a bad practice. `/opt` needs to be owned by `root:root` and software only updated by the administrator (by using sudo). And never execute a software with `sudo` just to workaround filesystem permissions.
> 
> /opt is owned by root, /opt/thunderbird is owned by me.

Yes, that's a bad practice.

**Comment by Ryushin** [comment]
> > > > > > Just use Thunderbird 91.3 via AppImage on Ubuntu/Mint. I also use it works fine
> > > > > 
> > > > > 
> > > > > Sadly solutions like AppImage, Snap, Flatpak, etc are all having the (dis)advantage to included all needed software libraries. So if a library needs a minor update from x.y.1 to x.y.2 because of a security bug, you won't get the update via your regular system updates. Instead you need to wait until a new Image for the software got created.
> > > > 
> > > > 
> > > > I just download the Thunderbird tar ball, put it in /opt, change the ownership to myself and it auto updates like normal.
> > > > Though I allowed Thunderbird to update to the latest version and the readability of the fonts being used was terrible, so I downgraded until I have time to get that sorted.
> > > 
> > > 
> > > That's a bad practice. `/opt` needs to be owned by `root:root` and software only updated by the administrator (by using sudo). And never execute a software with `sudo` just to workaround filesystem permissions.
> > 
> > 
> > /opt is owned by root, /opt/thunderbird is owned by me.
> 
> Yes, that's a bad practice.

Yea, well, it is not bad practice.  /opt/tomcat is owned by tomcat:tomact, and many other software packages do it the exact same way.  Having /opt/thunderbird set to 777 is wrong.  Having it owned by me is correct.  

Though for a multi user system a little cron job can have it auto upgrade by downloading and installing the latest version on a weekly basis:
```
#!/bin/bash
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin

cd /tmp/
wget -O ThunderbirdSetup.tar.bz2 "https://download.mozilla.org/?product=thunderbird-latest&os=linux64&lang=en-US"
tar xjf ThunderbirdSetup.tar.bz2 -C /opt/
chmod -fR 755 /opt/thunderbird
```

**Comment by MartinX3** [comment]
> > > > > > > Just use Thunderbird 91.3 via AppImage on Ubuntu/Mint. I also use it works fine
> > > > > > 
> > > > > > 
> > > > > > Sadly solutions like AppImage, Snap, Flatpak, etc are all having the (dis)advantage to included all needed software libraries. So if a library needs a minor update from x.y.1 to x.y.2 because of a security bug, you won't get the update via your regular system updates. Instead you need to wait until a new Image for the software got created.
> > > > > 
> > > > > 
> > > > > I just download the Thunderbird tar ball, put it in /opt, change the ownership to myself and it auto updates like normal.
> > > > > Though I allowed Thunderbird to update to the latest version and the readability of the fonts being used was terrible, so I downgraded until I have time to get that sorted.
> > > > 
> > > > 
> > > > That's a bad practice. `/opt` needs to be owned by `root:root` and software only updated by the administrator (by using sudo). And never execute a software with `sudo` just to workaround filesystem permissions.
> > > 
> > > 
> > > /opt is owned by root, /opt/thunderbird is owned by me.
> > 
> > Yes, that's a bad practice.
> 
> Yea, well, it is not bad practice.  /opt/tomcat is owned by tomcat:tomact, and many other software packages do it the exact same way.  Having /opt/thunderbird set to 777 is wrong.  Having it owned by me is correct.  
> 
> Though for a multi user system a little cron job can have it auto upgrade by downloading and installing the latest version on a weekly basis:
> ```
> #!/bin/bash
> export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin
> 
> cd /tmp/
> wget -O ThunderbirdSetup.tar.bz2 "https://download.mozilla.org/?product=thunderbird-latest&os=linux64&lang=en-US"
> tar xjf ThunderbirdSetup.tar.bz2 -C /opt/
> chmod -fR 755 /opt/thunderbird
> ```

You should use `~/.local/opt` for your user application.

**Comment by bbceg** [comment]
> FWIW, with Thunderbird 78 (and presumably later), I found [these instructions](https://emperor.dreamwidth.org/747469.html) on adding CalDAV support sufficient to get calendar support working without this plugin; mentioning it here in case that's useful...

Thanks for this, those instructions worked a treat on 91.4.1 for two calendars. The only downside seems to be a lack of tasks but I guess I can use the addon for that.

**Comment by ElizaZadura** [comment]
> I have the same issue. Found a solution!
> 
> Tools -> Options -> Advanced -> Config Editor Set calendar.google.enableEmailInvitations to True Close thunderbird, reopen, should work :) Also, go to Calendar, right click, select properties and make sure an email address is associated with the calendar. Then should be writable for other email accounts, not just the default, as well.

This still worked for me (TB 91.13.0). The option wasn't there, but got saved when I added it, set to true. Only one gmail account though.

**Comment by af7567** [comment]
Adding the `calendar.google.enableEmailInvitations` manually in TB 102 doesn't work for me any more.

**Comment by AGI-chandler** [comment]
@kewisch still a problem with TB 102.  `calendar.google.enableEmailInvitations=true` and I also tried adding my email to another calendar, looking at the config editor and noticing the `calendar.registry.<uuid>.imip.identity.key` was updated to `id#` with #=1 in my case.  so I tried setting the `calendar.registry.<uuid>.imip.identity.key` for my google calendar to `id1` also but it didn't help.  Hope you could please fix this ASAP as it's interfering with my work.

**Comment by AGI-chandler** [comment]
Ok I have 2 google accounts added, with 3 calendars from the 1st acct and 1 calendar from the 2nd.  2/3 of the calendars from the 1st acct have the option to assign an email to it, while the 3rd calendar plus the 1 calendar from the 2nd acct don't have the option to assign an email.  I compared all the `calendar.registry.*` settings and there wasn't anything different between them aside from the obvious URI's and names and whatnot, but nothing that indicated why 2 of them allowed an email to be assigned and 2 of them didn't.

But!  I found a solution!  @af7567 
For the calendar(s) that didn't allow assigning an email address, I went to https://calendar.google.com directly.  On the left side went to the calendar settings (3-dots menu > Settings and sharing), then exported the calendar.  It sent me a zip file with an ical file inside.  I extracted the ical file then went back to Google and just imported it back into my calendar (on the same page, Import & Export in the upper left (might have to create a new calendar first)).  So now you should have two copies of the same calendar.  Now go back into TB Calendar and add a new Google Calendar, select your existing account and click Find Calendars, it should show both of them now, put a checkmark in the new calendar and click Subscribe.  With the new calendar you should be able to assign an email to it!  If everything looks ok you can remove the old duplicate calendar from TB and delete it from your Google acct.

My guess is that our current calendars must be in some legacy format that is triggering this bug?  Creating a new google calendar may have updated it with the latest metadata or something.  I still have `calendar.google.enableAttendees`, `calendar.google.enableEmailInvitations`, and `calendar.google.sendEventNotifications` defined and set to `true`.  Just tried deleting all three of those preferences and restarting TB, it didn't change or delete my ability to assign an email to my calendars, so perhaps those preferences are now meaningless.  Hope it works for you!  Let us know...

**Comment by af7567** [comment]
@AGI-chandler I had no idea there was even meant to be an option to assign an email address to the calendar :) I have never seen that in the calendar properties before. But after upgrading Thunderbird to 102.4 today I had the option to assign an email address to one of my Google calendars and luckily it is the one I would like my invitations to go to. I don't have an email selection box on my other 2 calendars though for some reason.

**Comment by pedjas** [comment]
I stumbled too onto this issue. Thunderbird 102.11.0.
Unbelievable that this issue is so old and not resolved yet.


Fix that worked for me with Google account:

Add new Calendar (click + on Calendar List)
Select option On the Network
Enter Google email address and click on Find Calendars.
Follow the procedure of authentication.

You will be offered to import calendar, do it.

New calendar allows adding event by clicking on invitation.

If you are adding calendar account that already exists in your Thunderbird just make sure you name them so you now which is which as they will both show up. 

Disable old account until you are sure new one works. 

When sure you may delete old account.

**Comment by xsonic** [comment]
I have set `calendar.google.enableEmailInvitations=true` (don't know if necessary). For me, it only started working _after_ I deleted my local thunderbird calendar. I exported my TB calendar, and imported it into Google.

After deleteing all local TB calendars and selecting my email for the google calendar (Rightclick on calendar -> Properties -> Email), it started working and asking me, into which google calendar I want to import.

**Comment by KindlyThrive** [comment]
Strange, I have had this issue in Thunderbird for ages. Well, for the past few months it started working and it was great. Now with the most recent update, no more. :( I use 3 google calendars on 3 accounts and I have 4 more available. I wish it would at least just give us the calendar event file so we could import it. Or allow us to drop and drag the email into the calendar and understand what we wanted to do. :(
