### ISSUE TITLE
Addon purpose unclear on addons.thunderbird.net

### ISSUE THREAD

**Issue by Chealer** [kewisch/gdata-provider#954]
[This module's description on addons.thunderbird.net](https://addons.thunderbird.net/fr/thunderbird/addon/provider-for-google-calendar/) reads:

> This extension allows Thunderbird to read and write events and tasks to a Google Calendar.
> […]

Unless this extension is built in Thunderbird 128.10, which does not seem to be the case, this is confusing since stock Thunderbird can already read (and I believe write) to Google Calendar.

**Comment by kewisch** [comment]
It should work in Thunderbird 128. Is this a description error, or is something else not working? Do you have logs? https://github.com/kewisch/gdata-provider/wiki#enabling-debugging

**Comment by Chealer** [comment]
Hi @kewisch ,
Sorry, I cannot say if something is not working in this addon. Let me try clarifying what I reported here with some context.

I discovered this package when searching for an error message I was getting from Thunderbird when trying to dismiss an event in a Google calendar. I found [that discussion](https://github.com/kewisch/gdata-provider/discussions/708), which largely matches my problem. Yet, I could not tell if this package is guilty, because I do not even know if I am using this package.

Maybe "purpose" does not really convey the issue. I do understand this addon's purpose to a certain degree, but what I am wondering is what exactly it provides/is. It would help to indicate whether or not this addon is built in current Thunderbird versions.

**Comment by kewisch** [comment]
The dismissing reminders problem exists for quite a while, on the release versions due to how the updates are done. This is unfortunately not something I can easily change there. However, the beta has been rewritten from scratch and should not have this issue. https://kewisch.github.io/gdata-provider/beta.html

I've updated the screenshots, but they are the same as before.

Closing this issue since your actual problem is fixed in beta.

**Comment by Chealer** [comment]
Thank you for the update @kewisch. The screenshots sure help with this issue, but it remains unclear to me whether I am using this package, and I do not consider this issue resolved. I am glad to hear of a fix, but I am still not clear on whether (and how) this will help my Thunderbird.

**Comment by wsmwk** [comment]
@Chealer If YOU have not installed the add-on, then you are not using it.

Because your initial post asked about the **description** at https://addons.thunderbird.net/fr/thunderbird/addon/provider-for-google-calendar/ I think your question is "what does this add-on do that Thunderbird cannot"?  Put another way, why should I use this add-on?
 
@kewisch perhaps that sentence could be more precise?  https://github.com/kewisch/gdata-provider/wiki has a technical description, but not suitable for the average user.
